apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-service
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipment-service
  template:
    metadata:
      labels:
        app: shipment-service
    spec:
      containers:
        - name: shipment-service
          image: ghcr.io/tonibit/shipment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.kafka.svc.cluster.local:5432/order_service_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: shipment-service
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: shipment-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
